apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: volumes.example.com
  namespace: carbide-system
spec:
  group: example.com
  names:
    kind: Volume 
    plural: volumes 
    singular: volume
    shortNames:
      - vol
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec: # There is only one (required) field named "size" specifying the size in gib for the volume
              type: object
              properties:
                size:
                  type: integer
                  format: int32
              required: ["size"]
